name = "darkrebel-design"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "dark-rebel-db"
database_id = "9a4018e6-489e-4be4-a27f-4fdd0c5b00e3"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "darkrebel-files"
preview_bucket_name = "darkrebel-files-preview"

[env.production]
vars = { ADMIN_USERNAME = "darkrebel-admin", ADMIN_PASSWORD_HASH = "9a961c9ab9a9f790177617e009debfe57580c8c1eea61cdce27d618482bfa709", ADMIN_SESSION_SECRET = "PtZMvuWj93WRC0DBs/ut/WFMLGs0jXFq4GR5clMEzfg=" }