name = "darkrebel-design"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "dark-rebel-db"
database_id = "9a4018e6-489e-4be4-a27f-4fdd0c5b00e3"